# Generated by Django 5.1.3 on 2025-01-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BurgerHouse", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="additional_phone_number",
        ),
        migrations.RemoveField(
            model_name="order",
            name="comment",
        ),
        migrations.AddField(
            model_name="order",
            name="additional_phone",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Qo'shimcha telefon"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="note",
            field=models.TextField(blank=True, null=True, verbose_name="Eslatma"),
        ),
    ]
